#!/bin/bash

# AiShell Init 命令演示脚本

echo "=== AiShell Init 命令演示 ==="
echo ""
echo "此脚本展示如何使用 init 命令来配置 AI 模型提供商。"
echo ""
echo "可用的命令:"
echo ""
echo "1. 启动交互式配置:"
echo "   npm run init"
echo ""
echo "2. 或者使用："
echo "   npm run dev init"
echo ""
echo "3. 编译后运行:"
echo "   npm run build"
echo "   ./dist/index.js init"
echo ""
echo "=== 功能说明 ==="
echo ""
echo "✓ 支持三个模型提供商:"
echo "  - Claude (Anthropic)"
echo "  - Kimi (Moonshot)"
echo "  - DeepSeek"
echo ""
echo "✓ 交互流程:"
echo "  1. 选择模型提供商"
echo "  2. 输入 API Key"
echo "  3. 选择具体模型"
echo "  4. 确认并保存到 .env 文件"
echo ""
echo "✓ 配置会保存到:"
echo "  .env (项目根目录)"
echo ""
echo "=== 快速开始 ==="
echo ""
echo "运行以下命令开始配置:"
echo "  npm run init"
echo ""
